spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haohao_admin?characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
    hikari:
      max-lifetime: 10000
server:
  port: 7070